### ISSUE TITLE
Color or size Filters

### ISSUE THREAD

**Issue by sechix** [elevatorup/solidus_searchkick#1]
Hi,
I have installed your extension ok, but now I am trying to adapt my filters to this, but I don't know how, for example, I have :`# -------------------------------------------------------------------------------------
        # SIZE
        # option scope
 # -------------------------------------------------------------------------------------
        Spree::Product.add_search_scope :clothes_size_any do |*opts|
          option_scope = Spree::Product.includes(:variants_including_master)
          option_type = ProductFilters.clothes_size_filter[:option]

          opts.map { |opt|
            # opt is an array => ['option-name', [value1, value2, value3, ...]]
            option_scope= ProductFilters.option_with_values(option_scope, option_type, *opt)
           }
           option_scope
        end

        def ProductFilters.clothes_size_filter
          # Get an array of possible colours (option type of 'colour')
          # e.g. returns ["Gold", "Black", "White", "Silver", "Purple", "Multicoloured"]
          clothes_sizes = Spree::OptionValue.where(:option_type_id => Spree::OptionType.find_by_name("Clothes-size")).order("position").map(&:presentation).compact.uniq
          {
              :name => "Talla",
              :scope => :clothes_size_any,
              :conds =>  nil,
              :option => 'Clothes-size', # this is MANDATORY
              :class => "options two-column",
              :labels => clothes_sizes.map { |k| [k, k] }
          }
        end`

and standard filter for taxons:

`      def self.all_taxons

        taxons = Spree::Taxonomy.all.map { |t| [t.root] + t.root.descendants }.flatten
        {
          name:   'Categorías',
          scope:  :taxons_id_equals_any,
          labels: taxons.sort_by(&:name).map { |t| [t.name, t.id] },
          conds:  nil # not needed
        }
      end`

**Comment by thejbsmith** [comment]
@sechix, filtering is done a bit differently with this gem since it is now using Elasticsearch instead of Ransack (which is used by default). Due to this, any scopes or search_scopes on the product are not used by Elasticsearch.

Take a look at https://github.com/elevatorup/solidus_searchkick#filtering and https://github.com/elevatorup/solidus_searchkick/wiki/Advanced-Filtering to get a better handle on how to adapt your filters.

Here's a quick stab at how you might be able to adapt the clothes size filter. In this case, it is expected that the `search_data` method on Spree::Product sets `clothes_size` to the relevant value and products are indexed.
```
# lib/spree/core/searchkick_filters.rb

def self.clothes_size_filter
  conds = []

  clothes_sizes = Spree::OptionValue.where(:option_type_id => Spree::OptionType.find_by_name("Clothes-size")).order("position").map(&:presentation).compact.uniq

  clothes_sizes.each do |clothes_size|
    # conditions as: [label, elasticsearch_query]
    conds << [clothes_size, { match: { clothes_size: clothes_size } }]
  end

  {
    name: 'Clothes Size',
    scope: :clothes_size,
    conds:  Hash[*conds.flatten],
    labels: conds.map { |k, _v| [k, k] }
  }
end
```
Hope that helps, let me know how it goes.

**Comment by sechix** [comment]
thanks for your answer!!!
Understood, but I don't know why trying to search on filters I get error, with clothes_size_filter as you wrote:

NoMethodError in Spree::TaxonsController#show
undefined method `include?' for nil:NilClass

**Comment by thejbsmith** [comment]
Can you provide the code from Spree::TaxonsController#show around the line number where the error is being thrown?

**Comment by sechix** [comment]
It don't give exactly line because get error in a decorator line super, so crush in the solidus original code:

`module Spree
  class TaxonsController < Spree::StoreController
    rescue_from ActiveRecord::RecordNotFound, with: :render_404
    helper 'spree/products'

    respond_to :html

    def show
      @taxon = Spree::Taxon.find_by_permalink!(params[:id])
      return unless @taxon

      @searcher = build_searcher(params.merge(taxon: @taxon.id, include_images: true))
      @products = @searcher.retrieve_products
      @taxonomies = Spree::Taxonomy.includes(root: :children)
    end

    private

    def accurate_title
      if @taxon
        @taxon.seo_title
      else
        super
      end
    end
  end
end`

**Comment by thejbsmith** [comment]
Are you able to get the stack trace from the error? It may be on the page when you see this error, or you could always look at the terminal that is running your rails server. If we can figure out where that error is happening, then we can work on debugging it.

You could also take a look at the better_errors gem (https://github.com/charliesome/better_errors). This provides a great error page in the development environment, giving you a lot of information, as well as an active rails console at the point of the error.

**Comment by sechix** [comment]
thanks, but give me same information:
![captura de pantalla 2017-04-19 a las 20 06 29](https://cloud.githubusercontent.com/assets/24247266/25194797/d698f15a-253b-11e7-9d65-19ad892054e1.png)

**Comment by sechix** [comment]
Give error clothes_size but also price_filter that give in this gem as example, this is error with price_filter:

`Completed 500 Internal Server Error in 443ms (Searchkick: 344.6ms | ActiveRecord: 10.5ms)



Searchkick::InvalidQueryError - [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"failed to create query: {\n  \"bool\" : {\n    \"must\" : [\n      {\n        \"match_all\" : {\n          \"boost\" : 1.0\n        }\n      }\n    ],\n    \"filter\" : [\n      {\n        \"term\" : {\n          \"active\" : {\n            \"value\" : true,\n            \"boost\" : 1.0\n          }\n        }\n      },\n      {\n        \"term\" : {\n          \"currency\" : {\n            \"value\" : \"EUR\",\n            \"boost\" : 1.0\n          }\n        }\n      },\n      {\n        \"terms\" : {\n          \"price\" : [\n            \"€15,00 - €25,00\"\n          ],\n          \"boost\" : 1.0\n        }\n      },\n      {\n        \"term\" : {\n          \"taxon_ids\" : {\n            \"value\" : 2,\n            \"boost\" : 1.0\n          }\n        }\n      }\n    ],\n    \"disable_coord\" : false,\n   `

**Comment by thejbsmith** [comment]
Do you have a decorator for Spree::Taxon? If so, can you provide me with what you have in the `applicable_filters` method?

Can you also provide what you have set for `search_data` in the decorator for Spree::Product?

And lastly, after you updated the `search_data` method, did you reindex the products?

Sorry this one is so difficult to debug, hard to see what the issue is when Rails doesn't want to cooperate and just says the error is happening in `super`.

**Comment by sechix** [comment]
Don't worry, thank you for your patience.
These are my applicable_filters:

`	def applicable_filters
	  filters = []
	  
	  filters << Spree::Core::SearchkickFilters.price_filter if Spree::Core::SearchkickFilters.respond_to?(:price_filter)
	  filters << Spree::Core::SearchkickFilters.taxons_below(self)
	  filters << Spree::Core::SearchkickFilters.condition_filter if Spree::Core::SearchkickFilters.respond_to?(:condition_filter)

	  ## unless it's a root taxon? left open for demo purposes
      
	  # fs << Spree::Core::SearchkickFilters.price_filter if Spree::Core::SearchkickFilters.respond_to?(:price_filter)
	  filters << Spree::Core::SearchkickFilters.clothes_sizes_filter if Spree::Core::SearchkickFilters.respond_to?(:size_clothes_filter)
	  filters << Spree::Core::SearchkickFilters.color_filter if Spree::Core::SearchkickFilters.respond_to?(:color_filter)

	  filters << Spree::Core::SearchkickFilters.taxons_below(Spree::Taxon.find_by(name: 'Diseñadores'))
      filters << Spree::Core::SearchkickFilters.selective_style_filter if Spree::Core::SearchkickFilters.respond_to?(:selective_style_filter)
	  
      filters << Spree::Core::SearchkickFilters.selective_brand_filter(self) if Spree::Core::SearchkickFilters.respond_to?(:selective_brand_filter)
	  
	  filters
	end`
 
My search_data, I set reindex after add clothes_sizes, but I think is wrong, what its strange is price_filter crush too:

`  def search_data
    json = {
      name: name,
      description: description,
      active: available?,
      price: price,
      currency: cost_currency,
      sku: sku,
      conversions: orders.complete.count,
      taxon_ids: taxon_and_ancestors.map(&:id),
      taxon_names: taxon_and_ancestors.map(&:name),
      clothes_sizes: variants.map(&:clothes_sizes) 
    }

    json
  end
`

**Comment by thejbsmith** [comment]
@sechix, to debug, I'd start by commenting out all of the filters except for the price filter.
Then to debug the search_data method is going to output the data the correct data, use the rails console, find a product, and check it's search data
```
Spree::Product.find(1).search_data # use whatever product you'd like
```

If that looks good, make sure everything is index
```
Spree::Product.reindex
```
Then see if the price filter is working. 

Hopefully that will get things working properly, then the other filters can be debugged.

If that doesn't work, is there any way for me to see the code for the project that you're working on? That would help me be able to debug it a little better.

**Comment by sechix** [comment]
Hi @thejbsmith , I was searching a little bit. With only price filter I get same error. 

This is my product search_data using Spree::Product.find(1).search_data:

{:name=>"jersey de flores", :description=>"", :active=>true, :price=>#<BigDecimal:7f9e45e8b490,'0.39E2',9(18)>, :currency=>"EUR", :sku=>"", :conversions=>0, :taxon_ids=>[1, 2, 8, 9, 10], :taxon_names=>["woman", "Ropa", "Jersey", "Diseñadores", "French connection"]}

So, the index is ok. I add more debugging analyze and the error is due to a price format:

`"index":"spree_products_development_20170424152315177","caused_by":{"type":"number_format_exception","reason":"For input string: \"€5,00 - €10,00\""}}},"status":400}
`

I don't know why, any idea?
No problem to check my project code, thank you for your help!!

**Comment by thejbsmith** [comment]
What is the code that you have for the price filter?

Looking at that error, it looks like it might be searching the price field for the string "€5,00 - €10,00", as opposed to seeing if the price is within that range.

**Comment by sechix** [comment]
In searchkick_filters I have (the same as the gem):

`      def self.all_filters
        filters = []
        # Find all methods that ends with '_filter'
        filter_methods = Spree::Core::SearchkickFilters.methods.find_all { |m| m.to_s.end_with?('_filter') }
        filter_methods.each do |filter_method|
          filters << Spree::Core::SearchkickFilters.send(filter_method) if Spree::Core::SearchkickFilters.respond_to?(filter_method)
        end
        filters
      end

      def self.price_filter
        conds = [
          [Spree.t(:under_price, price: format_price(1)),   { range: { price: { lt: 1 } } }],
          ["#{format_price(1)} - #{format_price(5)}",       { range: { price: { from: 1, to: 5 } } }],
          ["#{format_price(5)} - #{format_price(10)}",      { range: { price: { from: 5, to: 10 } } }],
          ["#{format_price(10)} - #{format_price(15)}",     { range: { price: { from: 10, to: 15 } } }],
          ["#{format_price(15)} - #{format_price(25)}",     { range: { price: { from: 15, to: 25 } } }],
          ["#{format_price(25)} - #{format_price(50)}",     { range: { price: { from: 25, to: 50 } } }],
          ["#{format_price(50)} - #{format_price(100)}",    { range: { price: { from: 50, to: 100 } } }],
          [Spree.t(:over_price, price: format_price(100)),  { range: { price: { gt: 100 } } }]
        ]
        {
          name:   'Price',
          scope:  :price,
          conds:  Hash[*conds.flatten],
          labels: conds.map { |k, _v| [k, k] }
        }
      end

      def self.format_price(amount)
        Spree::Money.new(amount)
      end
`

**Comment by thejbsmith** [comment]
Would you be able to give me access to the project that you're working on? And provide some sample data to help me get set up? That way I can pull down the project and run it locally, which should help me figure out what the issue is. For any sensitive info, send it to the email on my Github profile instead of posting it in this issue.

**Comment by sechix** [comment]
Non sensitive info yet, because it not 'live'. Give me your email and I add you to heroku as a collaborator in order to download or check

**Comment by thejbsmith** [comment]
jim@jimsmithdesign.com

**Comment by sechix** [comment]
Hello, I added you in heroku, thanks a lot!!!!!!!

**Comment by thejbsmith** [comment]
@sechix, I believe I found out the underlying problems you were encountering.

1. In your `_filters.html.erb` partial, the second block of filters are scoped to `search` instead of `filter`. The first block of filters seems to be fine.

```
...
<input type="checkbox" id="<%= label %>" name="search[<%= filter[:scope].to_s %>][]" value="<%= val %>"
<%= params[:search] && params[:search][filter[:scope]] && params[:search][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
...
```
should be
```
...
<input type="checkbox" id="<%= label %>" name="filter[<%= filter[:scope].to_s %>][]" value="<%= val %>"
<%= params[:filter] && params[:filter][filter[:scope]] && params[:filter][filter[:scope]].include?(val.to_s) ? "checked" : "" %> />
...
```

2. There was an issue with the the gem was handling the params[:filter] was being handled with Rails 5. I made an update to the gem that should fix this.

3. You hadn't run into this yet, but the default indexing for currency was set to the `cost_currency`. I switched this to default to the `Spree::Config.currency`.


I believe that if you update your `_filters.html.erb` partial as mentioned above, and update to the latest version of the gem, that your search will work. Hope that helps!

**Comment by sechix** [comment]
Hello @thejbsmith , I have update gem but still not work. I see that last commit was 15 days ago. Have upload last changes?

**Comment by thejbsmith** [comment]
I had forgot to push the changes to Github (just pushed them now), but the updated gem had been pushed to RubyGems (https://rubygems.org/gems/solidus_searchkick).

**Comment by sechix** [comment]
Hi @thejbsmith , changed 
![image](https://cloud.githubusercontent.com/assets/24247266/25502193/fc2677a2-2b95-11e7-9120-483e4d99a764.png)

And extension updated, but continue with error (I have executed rake db:migrate and Spree::Product.reindex but nothing :(   )
![image](https://cloud.githubusercontent.com/assets/24247266/25502242/2c6c634a-2b96-11e7-9510-6dc4a5205345.png)

**Comment by thejbsmith** [comment]
I got it working on my machine. The only changes I made were updating the `_filters.html.erb` partial like you did in your last comment, and updating the `solidus_searchkick` gem to version `0.3.3`. Are you sure you are using version `0.3.3`? The update would require a `Spree::Product.reindex`, but it sounds like you already did that.

I'd give the reindex another try, make sure you shut down your server, and stop Spring (`bin/spring stop`) to make sure all old code is cleared. Then start the server again and see if you have any luck. If that doesn't work, I'm not sure how to debug further.

<img width="1211" alt="screen shot 2017-04-27 at 4 23 07 pm" src="https://cloud.githubusercontent.com/assets/408512/25502901/64be2fce-2b66-11e7-90d7-2408d33f9b8c.png">

The typeahead is a separate issue. Let's get the gem working for you first, then we can take a look at that.

**Comment by sechix** [comment]
Now works, but filter by price without taxes I need to include taxes. Other thing, taxes are indexed but to search I have included this but not works:
`      def self.all_taxons
        conds = []
        taxons = Spree::Taxonomy.all.map { |t| [t.root] + t.root.descendants }.flatten

        taxons.each do |taxons|
          # conditions as: [label, elasticsearch_query]
          conds << [taxons, { match: { taxon_names: taxons } }]
        end

        {
          name:   'Categorías',
          scope:  :taxons_id_equals_any,
          labels: taxons.sort_by(&:name).map { |t| [t.name, t.id] },
          conds:  Hash[*conds.flatten]
        }
      end`

For size closes, I don't know exactly how to index variants and properties in search_data

**Comment by thejbsmith** [comment]
@sechix, sorry for the delay. We had a few projects launching in the past few days and we've been pretty consumed by that.

Searching by taxons is already included with the gem, so you shouldn't need to build an additional filter. When you are building a searcher, just pass in the the taxon. In my `taxons_controller_decorator` I have the following code in my `show` action. This makes sure to only grab products in the taxon that is being passed in.

```
# taxons_controller_decorator.rb
def show
  searcher = build_searcher(params.merge(taxon: @taxon.id))
  @products = searcher.retrieve_products
end
```

As for indexing variants and properties, the way you want to handle that is up to you, and will depend on what filters you want to use around those items. For example, say you wanted to index the color of each variant of a product. Since the product itself comes in many colors, you would want to index those colors as an array on the product:

```
def search_data
  ...
  colors: [color_1, color_2, etc.],
  ...
end
```

You obviously don't want to hard-code colors there, but could replace that with a method that retrieves all of the colors as an array.

For properties, since they belong to a product you can simply index the property:
```
def search_data
  ...
  waterproof: property('waterproof'),
  ...
end
```

**Comment by sechix** [comment]
Finally solved but not autocomplite:

Also I need filter price by range slider with params[:minprice] and params[:maxprice] but I don't know how 
`# -------------------------------------------------------------------------------------
        # SIZE
        # option scope
 # -------------------------------------------------------------------------------------
        def self.clothes_size_filter  
            conds = []

            clothes_sizes = Spree::OptionValue.where(:option_type_id => Spree::OptionType.find_by_name("size_clothes")).order("position").map(&:presentation).compact.uniq

            clothes_sizes.each do |clothes_size|
              # conditions as: [label, elasticsearch_query]
                            conds << [clothes_size, { bool: { should: [
                                      terms: { clothes_sizes: clothes_sizes} ]
                                  }

                }]
            end

            {
              name: 'talla',
              scope: :clothes_size,
              conds:  Hash[*conds.flatten],
              labels: conds.map { |k, _v| [k, k] }
            }
        end
# -------------------------------------------------------------------------------------
        # COLOR
        # option scope
 # -------------------------------------------------------------------------------------
        def self.color_filter
            conds = []

            colors = Spree::OptionValue.where(:option_type_id => Spree::OptionType.find_by_name("color")).order("position").map(&:presentation).compact.uniq

            colors.each do |color|
              # conditions as: [label, elasticsearch_query]
              conds << [color, { bool: { should: [
                                      terms: { colors: colors} ]
                                  }

                }]
            end

            {
              name: 'color',
              scope: :color,
              conds:  Hash[*conds.flatten],
              labels: conds.map { |k, _v| [k, k] }
            }
        end`

And in search_data: 
`  def style
     property('style')
  end

  def colors

     variant_option_values_by_option_type.select { |option_type, _option_values| option_type.name == 'color' }.
      values.flatten.map(&:presentation)

   end
   def clothes_sizes
          variant_option_values_by_option_type.select { |option_type, _option_values| option_type.name == 'size_clothes' }.
      values.flatten.map(&:presentation)

   end`

**Comment by thejbsmith** [comment]
@sechix, right now I don't believe there is any way to handle a price slider since it wasn't built to handle dynamic values. Currently you need a condition for each option that could be passed back. In the future we could look at allowing a condition to accept a Proc, but off the top of my head I'm not sure how you would accomplish a price slider.
